name: Deploy to Server

on:
  push:
    branches:
      - main  # 你可以根据实际需求修改触发部署的分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up SSH key
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}

      # Step 3: Set up .env file
      - name: Set up .env file
        run: |
          echo "NEXT_PUBLIC_SERVICE_MODE=${{ secrets.NEXT_PUBLIC_SERVICE_MODE }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "KEY_VAULTS_SECRET=${{ secrets.KEY_VAULTS_SECRET }}" >> .env
          echo "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}" >> .env
          echo "CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }}" >> .env
          echo "CLERK_WEBHOOK_SECRET=${{ secrets.CLERK_WEBHOOK_SECRET }}" >> .env
          echo "S3_ACCESS_KEY_ID=${{ secrets.S3_ACCESS_KEY_ID }}" >> .env
          echo "S3_SECRET_ACCESS_KEY=${{ secrets.S3_SECRET_ACCESS_KEY }}" >> .env
          echo "S3_BUCKET=${{ secrets.S3_BUCKET }}" >> .env
          echo "S3_ENDPOINT=${{ secrets.S3_ENDPOINT }}" >> .env
          echo "S3_PUBLIC_DOMAIN=${{ secrets.S3_PUBLIC_DOMAIN }}" >> .env

      # Step 4: Copy files to server
      - name: Copy files to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_SSH_USER }}@${{ secrets.SERVER_IP }} "
            mkdir -p ${{ secrets.SERVER_DEPLOY_PATH }} &&
            rm -rf ${{ secrets.SERVER_DEPLOY_PATH }}/* &&
            exit"
          scp -o StrictHostKeyChecking=no -r * ${{ secrets.SERVER_SSH_USER }}@${{ secrets.SERVER_IP }}:${{ secrets.SERVER_DEPLOY_PATH }}

      # Step 5: Run deployment script on server
      - name: Run deployment script on server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_SSH_USER }}@${{ secrets.SERVER_IP }} "
            cd ${{ secrets.SERVER_DEPLOY_PATH }} &&
            docker-compose down &&
            docker-compose up -d"
